
<!-- AUTOGENERATED BY grunt-ngbs-forms FROM <%= filepath %>, PLEASE, DON'T MODIFY IT -->
<form role="form" name="<%= name %>" novalidate ng-init="<%= name %>.sent = false;" ng-submit="<%= name %>.sent = true; <%= trySubmit %><%= name %>.$setPristine(); <%= submit %>" autocomplete="off"><% if (!noFieldset) { %>
<fieldset><% } %>
