
<!-- AUTOGENERATED BY grunt-ngbs-forms FROM <%= filepath %>, PLEASE, DON'T MODIFY IT -->
<form role="form" name="<%= name %>" novalidate ng-init="<%= protectedName %>.sent = false;" ng-submit="<%= protectedName %>.sent = true; <%= trySubmit %><%= protectedName %>.$setPristine(); <%= submit %>">
<fieldset>
